/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.OldAgeOrganizationAdminRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.Utils.TableColors;
import Business.Utils.Validation;
import Business.WorkQueue.FoodWorkRequest;
import Business.WorkQueue.FoodSafetyInspectionWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jayesh Nagarkar
 */
public class OldAgeAdminWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form OrphanageAdminWorkAreaJPanel
     */
    JPanel userProcessContainer;
    UserAccount account;
    Organization organization;Enterprise enterprise;
    Network network;
    EcoSystem business;
    Validation validation;
    
    public OldAgeAdminWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise,Network network, EcoSystem business) {
        initComponents();
        organizationJTable.getTableHeader().setDefaultRenderer(new TableColors());
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.organization = organization;
        this.network = network;
        this.business = business;
        organizationJTable.getTableHeader().setDefaultRenderer(new TableColors());
        populateTable();
    }
    
    public void populateTable(){
        DefaultTableModel model = (DefaultTableModel) organizationJTable.getModel();
        
        model.setRowCount(0);
        for (WorkRequest request : account.getWorkQueue().getWorkRequestList()){
            if(request instanceof FoodSafetyInspectionWorkRequest) continue;
            FoodWorkRequest req = (FoodWorkRequest)request;
            System.out.println(req);
            Object[] row = new Object[7];
            row[0] = req;         //--jayesh   row[0] = request.getMessage(); 
            row[1] = req.getRequestDate();
            row[2] = req.getDeliveryTimestamp();
            row[3] = req.getStatus();
            row[4] = req.getNoOfServings();
            
            row[5] = req.getDonorOrganization();
            if(req.getDonorOrganization() == null)row[5] = "To be assigned";
            
            row[6] = req.getDeliveryUser();
            if(req.getDeliveryUser() == null)row[6] = "To be assigned";
            
            
            model.addRow(row);
        }
    }
    public void resetTextField(){
        txtNoOfServings.setText("");
        txtContactNumber.setText("");
        txtEmailId.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        organizationJTable = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtNoOfServings = new javax.swing.JTextField();
        txtContactNumber = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtEmailId = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        organizationJTable.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        organizationJTable.setForeground(new java.awt.Color(25, 56, 82));
        organizationJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Order ID", "Order request Time", "Order Delivery Time", "Status", "No of Servings", "Donor Organization Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        organizationJTable.setSelectionBackground(new java.awt.Color(56, 90, 174));
        jScrollPane1.setViewportView(organizationJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 111, 750, 157));

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(25, 56, 82));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("MANAGE OLDAGE ORGANIZATION");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 34, 581, -1));

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(25, 56, 82));
        jLabel8.setText("No of Servings");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, 110, -1));

        txtNoOfServings.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        txtNoOfServings.setForeground(new java.awt.Color(25, 56, 82));
        txtNoOfServings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNoOfServingsActionPerformed(evt);
            }
        });
        txtNoOfServings.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNoOfServingsKeyPressed(evt);
            }
        });
        add(txtNoOfServings, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 320, 210, 30));

        txtContactNumber.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        txtContactNumber.setForeground(new java.awt.Color(25, 56, 82));
        txtContactNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContactNumberActionPerformed(evt);
            }
        });
        add(txtContactNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 370, 210, 30));

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(25, 56, 82));
        jLabel7.setText("Contact Number");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 380, -1, -1));

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(25, 56, 82));
        jLabel9.setText("Email id");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 420, -1, -1));

        txtEmailId.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        txtEmailId.setForeground(new java.awt.Color(25, 56, 82));
        txtEmailId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailIdActionPerformed(evt);
            }
        });
        add(txtEmailId, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 420, 210, 30));

        btnSubmit.setBackground(new java.awt.Color(255, 255, 255));
        btnSubmit.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnSubmit.setForeground(new java.awt.Color(25, 56, 82));
        btnSubmit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSubmit.setText("Submit");
        btnSubmit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnSubmit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSubmitMousePressed(evt);
            }
        });
        add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 470, 138, 35));
    }// </editor-fold>//GEN-END:initComponents

    private void txtNoOfServingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNoOfServingsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNoOfServingsActionPerformed

    private void txtNoOfServingsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNoOfServingsKeyPressed
        // TODO add your handling code here:
        Validation.integerValidator(evt, txtNoOfServings);
    }//GEN-LAST:event_txtNoOfServingsKeyPressed

    private void txtContactNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContactNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContactNumberActionPerformed

    private void txtEmailIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailIdActionPerformed

    private void btnSubmitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubmitMousePressed
        System.out.println("OrphanageAdmin line number 265");
        if (!Validation.emailValidator(txtEmailId.getText())) {
            JOptionPane.showMessageDialog(null, "entered email is not in valid format");
            return;
        }else if(!Validation.phoneNumberValidator(txtContactNumber.getText())){
            JOptionPane.showMessageDialog(null, "phone number is not in right format");
            return;
        }
        FoodWorkRequest request = new FoodWorkRequest();

        //request.setDeliveryTimestamp(new Date());
        request.setStatus("Requested");
        request.setRequestDate(new Date());

        request.setNoOfServings(Integer.parseInt(txtNoOfServings.getText()));
        request.setRequestingOrganiztionName(organization);
        request.setRequestingOrganizationUser(account);

        request.setRequestingOrganizationType(organization.getType());

        request.setEmailId(txtEmailId.getText());

        account.getWorkQueue().getWorkRequestList().add(request);
        organization.getWorkQueue().getWorkRequestList().add(request);

        JOptionPane.showMessageDialog(null, "Request Sent To food DonationEnterprise Admin");
        populateTable();
        resetTextField();
        System.out.println("oraphanage line number 291");

    }//GEN-LAST:event_btnSubmitMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnSubmit;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable organizationJTable;
    private javax.swing.JTextField txtContactNumber;
    private javax.swing.JTextField txtEmailId;
    private javax.swing.JTextField txtNoOfServings;
    // End of variables declaration//GEN-END:variables
}
