/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.PartyOrganizationAdmin;

import Business.Enterprise.Delivery;
import Business.Enterprise.Enterprise;
import Business.Menu.Item;
import Business.Menu.Menu;
import Business.Network.Network;
import Business.Organization.DriverOrganization;
import Business.Organization.Organization;
import Business.Organization.RestaurantOrganization;
import Business.UserAccount.UserAccount;
import Business.Utils.TableColors;
import Business.WorkQueue.FoodWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.Image;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import ui.RestaurantAdminRole.RestaurantAdminWorkAreaJPanel;

/**
 *
 * @author Jayesh Nagarkar
 */
public class PartyOrganizationProcessOrderJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PartyOrganizationProcessOrderJPanel
     */
    JPanel userProcessContainer;
    UserAccount account;
    Organization organization;
    Network network;
    FoodWorkRequest requestReq;
    int totalNumberOfServings;
    
    public PartyOrganizationProcessOrderJPanel(JPanel userProcessContainer,UserAccount account,Organization organization,Network network,FoodWorkRequest requestReq) {
        initComponents();
        
        restaurantAdminMenuJTable.getTableHeader().setDefaultRenderer(new TableColors());
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.organization = organization;
        this.network = network;
        this.requestReq = requestReq;
        txtTotalNumberOfRequiredServings.setText(Integer.toString(requestReq.getNoOfServings()));
        populateMenu();
        populateCombo();
    }
    public void backButton(){

        
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        RestaurantAdminWorkAreaJPanel rawp = (RestaurantAdminWorkAreaJPanel) component;
        rawp.populateRestaurantAdminRequestDashboard();
        rawp.populateMenuTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }
    public void populateMenu(){
        DefaultTableModel model = (DefaultTableModel) restaurantAdminMenuJTable.getModel();
        model.setRowCount(0);
        RestaurantOrganization org = (RestaurantOrganization)organization;
        for(Item item : org.getMenu().getItemList() ){
            Object[] row = new Object[3];
            row[0] = item;
            row[1] = item.getDescription();
            row[2] = item.getNumberOfServings();
            model.addRow(row);
            
        }
    }
    
    public void populateCombo(){
        comboDeliveryManList.removeAllItems();
//        for(Organization org : enterprise.getOrganizationDirectory().getOrganizationList()){
//            if(org instanceof DeliveryManOrganization){
//                for(UserAccount ua : org.getUserAccountDirectory().getUserAccountList()){
//                    comboDeliveryManList.addItem(ua.getUsername());
//                }
//            }
//        }
        for(Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList() ){
            if(enterprise instanceof Delivery ){
                for(Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
                    for(UserAccount account : organization.getUserAccountDirectory().getUserAccountList()){
                        comboDeliveryManList.addItem(account.getUsername());
                    }
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblImage = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        restaurantAdminMenuJTable = new javax.swing.JTable();
        lblQuantity1 = new javax.swing.JLabel();
        btnDeleteItem2 = new javax.swing.JLabel();
        comboDeliveryManList = new javax.swing.JComboBox<>();
        lblQuantity = new javax.swing.JLabel();
        btnDeleteItem3 = new javax.swing.JLabel();
        btnAddItem = new javax.swing.JLabel();
        btnUploadImage1 = new javax.swing.JLabel();
        txtNoOfServing = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        lblImage1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        restaurantAdminMenuJTable1 = new javax.swing.JTable();
        txtTotalNumberOfRequiredServings = new javax.swing.JTextField();
        lblQuantity2 = new javax.swing.JLabel();
        btnDeleteItem4 = new javax.swing.JLabel();
        comboDeliveryManList1 = new javax.swing.JComboBox<>();
        lblQuantity3 = new javax.swing.JLabel();
        btnDeleteItem5 = new javax.swing.JLabel();
        btnAddItem1 = new javax.swing.JLabel();
        btnUploadImage4 = new javax.swing.JLabel();
        txtNoOfServing1 = new javax.swing.JTextField();
        btnUploadImage = new javax.swing.JLabel();
        btnUploadImage2 = new javax.swing.JLabel();
        txtTotalNumberOfServings = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtImagePath = new javax.swing.JTextField();
        txtTotalNumberOfServings2 = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(lblImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 460, 330, 180));

        restaurantAdminMenuJTable.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        restaurantAdminMenuJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Item ID", "Food Description", "No Of Serves"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        restaurantAdminMenuJTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                restaurantAdminMenuJTableMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(restaurantAdminMenuJTable);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, -1, 180));

        lblQuantity1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lblQuantity1.setForeground(new java.awt.Color(25, 56, 82));
        lblQuantity1.setText("No Of Servings");
        lblQuantity1.setToolTipText("");
        add(lblQuantity1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, 110, -1));

        btnDeleteItem2.setBackground(new java.awt.Color(255, 255, 255));
        btnDeleteItem2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnDeleteItem2.setForeground(new java.awt.Color(25, 56, 82));
        btnDeleteItem2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnDeleteItem2.setText("Send Order");
        btnDeleteItem2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnDeleteItem2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSendMousePressed(evt);
            }
        });
        add(btnDeleteItem2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 650, 138, 35));

        comboDeliveryManList.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        comboDeliveryManList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(comboDeliveryManList, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 660, 134, -1));

        lblQuantity.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lblQuantity.setForeground(new java.awt.Color(25, 56, 82));
        lblQuantity.setText("Delivery Man:");
        lblQuantity.setToolTipText("");
        add(lblQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 660, 90, -1));

        btnDeleteItem3.setBackground(new java.awt.Color(255, 255, 255));
        btnDeleteItem3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnDeleteItem3.setForeground(new java.awt.Color(25, 56, 82));
        btnDeleteItem3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnDeleteItem3.setText("<<  Back");
        btnDeleteItem3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnDeleteItem3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnDeleteItem3btnBackMousePressed(evt);
            }
        });
        add(btnDeleteItem3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 138, 35));

        btnAddItem.setBackground(new java.awt.Color(255, 255, 255));
        btnAddItem.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnAddItem.setForeground(new java.awt.Color(25, 56, 82));
        btnAddItem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAddItem.setText("Add Item ");
        btnAddItem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnAddItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnAddItemMousePressed(evt);
            }
        });
        add(btnAddItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 370, 138, 35));

        btnUploadImage1.setBackground(new java.awt.Color(255, 255, 255));
        btnUploadImage1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnUploadImage1.setForeground(new java.awt.Color(25, 56, 82));
        btnUploadImage1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnUploadImage1.setText("View Food Image");
        btnUploadImage1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnUploadImage1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnUploadImage1Pressed(evt);
            }
        });
        add(btnUploadImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 420, 138, 20));

        txtNoOfServing.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        txtNoOfServing.setForeground(new java.awt.Color(25, 56, 82));
        txtNoOfServing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNoOfServingActionPerformed(evt);
            }
        });
        add(txtNoOfServing, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 370, 150, 30));

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(lblImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 460, 330, 180));

        restaurantAdminMenuJTable1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        restaurantAdminMenuJTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Food Description", "No Of Serves"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(restaurantAdminMenuJTable1);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, -1, 180));

        txtTotalNumberOfRequiredServings.setEditable(false);
        txtTotalNumberOfRequiredServings.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        txtTotalNumberOfRequiredServings.setForeground(new java.awt.Color(25, 56, 82));
        txtTotalNumberOfRequiredServings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalNumberOfRequiredServingsActionPerformed(evt);
            }
        });
        jPanel1.add(txtTotalNumberOfRequiredServings, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 100, 60, 30));

        lblQuantity2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lblQuantity2.setForeground(new java.awt.Color(25, 56, 82));
        lblQuantity2.setText("No Of Servings");
        lblQuantity2.setToolTipText("");
        jPanel1.add(lblQuantity2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, 110, -1));

        btnDeleteItem4.setBackground(new java.awt.Color(255, 255, 255));
        btnDeleteItem4.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnDeleteItem4.setForeground(new java.awt.Color(25, 56, 82));
        btnDeleteItem4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnDeleteItem4.setText("Send Order");
        btnDeleteItem4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnDeleteItem4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnDeleteItem4btnSendMousePressed(evt);
            }
        });
        jPanel1.add(btnDeleteItem4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 650, 138, 35));

        comboDeliveryManList1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        comboDeliveryManList1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(comboDeliveryManList1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 660, 134, -1));

        lblQuantity3.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lblQuantity3.setForeground(new java.awt.Color(25, 56, 82));
        lblQuantity3.setText("Delivery Man:");
        lblQuantity3.setToolTipText("");
        jPanel1.add(lblQuantity3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 660, 90, -1));

        btnDeleteItem5.setBackground(new java.awt.Color(255, 255, 255));
        btnDeleteItem5.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnDeleteItem5.setForeground(new java.awt.Color(25, 56, 82));
        btnDeleteItem5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnDeleteItem5.setText("<<  Back");
        btnDeleteItem5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnDeleteItem5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnDeleteItem5btnBackMousePressed(evt);
            }
        });
        jPanel1.add(btnDeleteItem5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 138, 35));

        btnAddItem1.setBackground(new java.awt.Color(255, 255, 255));
        btnAddItem1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnAddItem1.setForeground(new java.awt.Color(25, 56, 82));
        btnAddItem1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAddItem1.setText("Add Item ");
        btnAddItem1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnAddItem1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnAddItem1MousePressed(evt);
            }
        });
        jPanel1.add(btnAddItem1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 370, 138, 35));

        btnUploadImage4.setBackground(new java.awt.Color(255, 255, 255));
        btnUploadImage4.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnUploadImage4.setForeground(new java.awt.Color(25, 56, 82));
        btnUploadImage4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnUploadImage4.setText("View Food Image");
        btnUploadImage4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnUploadImage4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnUploadImage4Pressed(evt);
            }
        });
        jPanel1.add(btnUploadImage4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 420, 138, 20));

        txtNoOfServing1.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        txtNoOfServing1.setForeground(new java.awt.Color(25, 56, 82));
        txtNoOfServing1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNoOfServing1ActionPerformed(evt);
            }
        });
        jPanel1.add(txtNoOfServing1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 370, 150, 30));

        btnUploadImage.setBackground(new java.awt.Color(255, 255, 255));
        btnUploadImage.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnUploadImage.setForeground(new java.awt.Color(25, 56, 82));
        btnUploadImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnUploadImage.setText("Required Number Of Servings");
        btnUploadImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnUploadImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnUploadImagePressed(evt);
            }
        });
        jPanel1.add(btnUploadImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 220, 30));

        btnUploadImage2.setBackground(new java.awt.Color(255, 255, 255));
        btnUploadImage2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnUploadImage2.setForeground(new java.awt.Color(25, 56, 82));
        btnUploadImage2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnUploadImage2.setText("Total Number Of Servings:");
        btnUploadImage2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnUploadImage2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnUploadImage2Pressed(evt);
            }
        });
        jPanel1.add(btnUploadImage2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, 220, 30));

        txtTotalNumberOfServings.setEditable(false);
        txtTotalNumberOfServings.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        txtTotalNumberOfServings.setForeground(new java.awt.Color(25, 56, 82));
        txtTotalNumberOfServings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalNumberOfServingsActionPerformed(evt);
            }
        });
        jPanel1.add(txtTotalNumberOfServings, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 130, 60, 30));

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(25, 56, 82));
        jLabel8.setText("Party Build Order");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, 190, -1));

        txtImagePath.setFont(new java.awt.Font("SansSerif", 2, 10)); // NOI18N
        jPanel1.add(txtImagePath, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 420, 310, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 720));

        txtTotalNumberOfServings2.setEditable(false);
        txtTotalNumberOfServings2.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        txtTotalNumberOfServings2.setForeground(new java.awt.Color(25, 56, 82));
        txtTotalNumberOfServings2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalNumberOfServings2ActionPerformed(evt);
            }
        });
        add(txtTotalNumberOfServings2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 130, 60, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void restaurantAdminMenuJTableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_restaurantAdminMenuJTableMousePressed
        // TODO add your handling code here:
       int selectedRequestTableRow = restaurantAdminMenuJTable.getSelectedRow();            //bottom table
        
        
        if (selectedRequestTableRow < 0){
            
            JOptionPane.showMessageDialog(null, "Please Select a request row from Menu tables!");
            return;
        }
        
        Item item = (Item)restaurantAdminMenuJTable.getValueAt(selectedRequestTableRow, 0);
        
        
        //---------------------------------
       
        System.out.println(item.getImagePath());
        String imagePath = item.getImagePath();
        if(imagePath != null){
            imagePath = imagePath.replace("\\","\\\\");
        }
        
        ImageIcon icon = new ImageIcon(imagePath);
        Image image = icon.getImage().getScaledInstance(lblImage.getWidth(), lblImage.getHeight(), java.awt.Image.SCALE_SMOOTH);
        icon = new ImageIcon(image);
        lblImage.setIcon(icon);
        txtImagePath.setText(imagePath);

        


        
    }//GEN-LAST:event_restaurantAdminMenuJTableMousePressed

    private void btnSendMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSendMousePressed
        // TODO add your handling code here:
        UserAccount ua = null;
        for(Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()){
            if(enterprise instanceof Delivery){
                for(Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
                    if(organization instanceof DriverOrganization ){
                        
                        ua = organization.getUserAccountDirectory().searchUser((String)comboDeliveryManList.getSelectedItem());
                    }
                }
            }
        }
        requestReq.setStatus("Sent");
        requestReq.setDeliveryUser(ua);
        requestReq.setDeliveryTimestamp(new Date());
        requestReq.setDonorOrganization(organization);
        requestReq.setDonorOrganizationType(Organization.Type.Restaurant);
        ua.getWorkQueue().addRequest(requestReq);
        JOptionPane.showMessageDialog(null, "Food Order sent successfully!");
        backButton();

        
    }//GEN-LAST:event_btnSendMousePressed

    private void btnDeleteItem3btnBackMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteItem3btnBackMousePressed
        // TODO add your handling code here:
       

    }//GEN-LAST:event_btnDeleteItem3btnBackMousePressed

    private void btnAddItemMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddItemMousePressed
        // TODO add your handling code here:
        int quantity = Integer.parseInt(txtNoOfServing.getText());
        int selectedRequestTableRow = restaurantAdminMenuJTable.getSelectedRow();            //bottom table
        
        
        if (selectedRequestTableRow < 0){
            
            JOptionPane.showMessageDialog(null, "Please Select a request row from Menu tables!");
            return;
        }
        
        Item item = (Item)restaurantAdminMenuJTable.getValueAt(selectedRequestTableRow, 0);
        
        
        //---------------------------------
       
        System.out.println(item.getImagePath());
        String imagePath = item.getImagePath();
        if(imagePath != null){
            imagePath = imagePath.replace("\\","\\\\");
        }
        
        ImageIcon icon = new ImageIcon(imagePath);
        Image image = icon.getImage().getScaledInstance(lblImage.getWidth(), lblImage.getHeight(), java.awt.Image.SCALE_SMOOTH);
        icon = new ImageIcon(image);
        lblImage.setIcon(icon);
        txtImagePath.setText("");

        
        
        //--------------------------------
        
        if(quantity > item.getNumberOfServings()) {
            JOptionPane.showMessageDialog(null, "selected item has left less number of servings!");
            return;
        }
        item.setNumberOfServings(item.getNumberOfServings() - quantity);
        Menu cart = new Menu();
        cart.addItem(item);
        txtNoOfServing.setText("");
        totalNumberOfServings = totalNumberOfServings + quantity;
        txtTotalNumberOfServings.setText(Integer.toString(totalNumberOfServings));
        
        JOptionPane.showMessageDialog(null, "Item added into the cart!");
        System.out.println(item.getImagePath());
        
        
        icon = new ImageIcon("");
        image = icon.getImage().getScaledInstance(lblImage.getWidth(), lblImage.getHeight(), java.awt.Image.SCALE_SMOOTH);
        icon = new ImageIcon(image);
        lblImage.setIcon(icon);
        
        populateMenu();

        
    }//GEN-LAST:event_btnAddItemMousePressed

    private void btnUploadImage1Pressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUploadImage1Pressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUploadImage1Pressed

    private void txtNoOfServingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNoOfServingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNoOfServingActionPerformed

    private void txtTotalNumberOfRequiredServingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalNumberOfRequiredServingsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalNumberOfRequiredServingsActionPerformed

    private void btnDeleteItem4btnSendMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteItem4btnSendMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteItem4btnSendMousePressed

    private void btnDeleteItem5btnBackMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteItem5btnBackMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteItem5btnBackMousePressed

    private void btnAddItem1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddItem1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddItem1MousePressed

    private void btnUploadImage4Pressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUploadImage4Pressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUploadImage4Pressed

    private void txtNoOfServing1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNoOfServing1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNoOfServing1ActionPerformed

    private void btnUploadImagePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUploadImagePressed
        // TODO add your handling code here:
        // TODO add your handling code here:
      
    }//GEN-LAST:event_btnUploadImagePressed

    private void btnUploadImage2Pressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUploadImage2Pressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUploadImage2Pressed

    private void txtTotalNumberOfServingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalNumberOfServingsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalNumberOfServingsActionPerformed

    private void txtTotalNumberOfServings2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalNumberOfServings2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalNumberOfServings2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnAddItem;
    private javax.swing.JLabel btnAddItem1;
    private javax.swing.JLabel btnDeleteItem2;
    private javax.swing.JLabel btnDeleteItem3;
    private javax.swing.JLabel btnDeleteItem4;
    private javax.swing.JLabel btnDeleteItem5;
    private javax.swing.JLabel btnUploadImage;
    private javax.swing.JLabel btnUploadImage1;
    private javax.swing.JLabel btnUploadImage2;
    private javax.swing.JLabel btnUploadImage4;
    private javax.swing.JComboBox<String> comboDeliveryManList;
    private javax.swing.JComboBox<String> comboDeliveryManList1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblImage1;
    private javax.swing.JLabel lblQuantity;
    private javax.swing.JLabel lblQuantity1;
    private javax.swing.JLabel lblQuantity2;
    private javax.swing.JLabel lblQuantity3;
    private javax.swing.JTable restaurantAdminMenuJTable;
    private javax.swing.JTable restaurantAdminMenuJTable1;
    private javax.swing.JTextField txtImagePath;
    private javax.swing.JTextField txtNoOfServing;
    private javax.swing.JTextField txtNoOfServing1;
    private javax.swing.JTextField txtTotalNumberOfRequiredServings;
    private javax.swing.JTextField txtTotalNumberOfServings;
    private javax.swing.JTextField txtTotalNumberOfServings2;
    // End of variables declaration//GEN-END:variables
}
