/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.FoodDonationAdminRole;

import Business.Organization.Organization;
import Business.Organization.OrganizationDirectory;
import Business.Utils.TableColors;
import javax.swing.JPanel;

/**
 *
 * @author Jayesh Nagarkar
 */
public class FoodDonationManageRequest extends javax.swing.JPanel {

    /**
     * Creates new form FoodDonationManageRequest
     */
    public FoodDonationManageRequest(JPanel rightSystemAdminPanel, OrganizationDirectory organizationDirectory) {
        initComponents();
        requestJTable.getTableHeader().setDefaultRenderer(new TableColors());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        requestJTable = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        addJButton = new javax.swing.JButton();
        addJButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        requestJTable.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        requestJTable.setForeground(new java.awt.Color(25, 56, 82));
        requestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Name", "User Id", "Organization Type", "Network", "Status", "Enterprise Admin"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        requestJTable.setSelectionBackground(new java.awt.Color(56, 90, 174));
        jScrollPane1.setViewportView(requestJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 820, 116));

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(25, 56, 82));
        jLabel4.setText("MANAGE FOOD DONATION ENTERPRISE MANAGE REGISTRATION");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/emergency512icon.png"))); // NOI18N
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 22, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/emergencyEmployee512xxx.png"))); // NOI18N
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 320, -1, -1));

        addJButton.setBackground(new java.awt.Color(255, 255, 255));
        addJButton.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        addJButton.setForeground(new java.awt.Color(25, 56, 82));
        addJButton.setText("Assign to me");
        addJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addJButtonActionPerformed(evt);
            }
        });
        add(addJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, -1, -1));

        addJButton1.setBackground(new java.awt.Color(255, 255, 255));
        addJButton1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        addJButton1.setForeground(new java.awt.Color(25, 56, 82));
        addJButton1.setText("Process");
        addJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addJButton1ActionPerformed(evt);
            }
        });
        add(addJButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void addJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addJButtonActionPerformed

//        Organization organization = (Organization) organizationEmpJComboBox.getSelectedItem();
//        String name = nameJTextField.getText();
//        if(!name.isEmpty()){
//            organization.getEmployeeDirectory().createEmployee(name);
//            populateTable(organization);
//            nameJTextField.setText("");
//            JOptionPane.showMessageDialog(null, "Employee created sucessfully!");
//            resetFields();
//        } else{
//            JOptionPane.showMessageDialog(null, "Enter employee name!");
//        }
    }//GEN-LAST:event_addJButtonActionPerformed

    private void addJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addJButton1ActionPerformed

//        Organization organization = (Organization) organizationEmpJComboBox.getSelectedItem();
//        String name = nameJTextField.getText();
//        if(!name.isEmpty()){
//            organization.getEmployeeDirectory().createEmployee(name);
//            populateTable(organization);
//            nameJTextField.setText("");
//            JOptionPane.showMessageDialog(null, "Employee created sucessfully!");
//            resetFields();
//        } else{
//            JOptionPane.showMessageDialog(null, "Enter employee name!");
//        }
    }//GEN-LAST:event_addJButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addJButton;
    private javax.swing.JButton addJButton1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable requestJTable;
    // End of variables declaration//GEN-END:variables
}
