/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.DriverOrganizationAdminRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.Utils.TableColors;
import Business.WorkQueue.FoodWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import ui.RestaurantAdminRole.RestaurantProcessOrderJPaneln;

/**
 *
 * @author Jayesh Nagarkar
 */
public class DriverOrganizationAdminWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DriverOrganizationAdminWorkAreaJPanel
     */
    JPanel userProcessContainer; 
    UserAccount account; 
    Organization organization; 
    Enterprise enterprise;
    Network network;EcoSystem business;
    
    public DriverOrganizationAdminWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise,Network network, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.organization = organization;
        this.enterprise = enterprise;
        this.network = network;
        this.business = business;
        
        driverJTable.getTableHeader().setDefaultRenderer(new TableColors());
        populateTable();
        
        lblDriverName.setText(account.getEmployee().getName());
        lblDriverAge.setText(Integer.toString(account.getEmployee().getAge()));
        lblDriverAge.setText(Integer.toString(account.getEmployee().getAge()));
        
        lblDriverSex.setText(account.getEmployee().getSex());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void populateTable(){
        DefaultTableModel model = (DefaultTableModel) driverJTable.getModel();
        model.setRowCount(0);
        
        for(WorkRequest request : account.getWorkQueue().getWorkRequestList()){
            FoodWorkRequest req = (FoodWorkRequest)request;
            Object[] row = new Object[7]; 
            row[0] = req;
            //row[1] = req.getDeliveryUser();
            if(req.getDonorOrganization() != null) row[1] = req.getDonorOrganization().getLocationPoint();
            
            row[2] = req.getRequestingOrganiztionName().getLocationPoint();
            row[3] = req.getDonorOrganization();
            
            row[4] = req.getRequestingOrganiztionName();
            row[5] = req.getStatus();
            
            row[6]= req.getDeliveryTimestamp();
            
            model.addRow(row);
        }
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        driverJTable = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        lblDriverSex = new javax.swing.JLabel();
        lblDriverAge = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblDriverName = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnDeleteItem2 = new javax.swing.JLabel();
        btnDeleteItem3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        driverJTable.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        driverJTable.setForeground(new java.awt.Color(25, 56, 82));
        driverJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Order ID", "Pick Up Location", "Delivery Loaction", "Donor Organization", "Requesting Organization", "Delivery Status", "TimeStamp"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        driverJTable.setSelectionBackground(new java.awt.Color(56, 90, 174));
        jScrollPane1.setViewportView(driverJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 1110, 157));

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(25, 56, 82));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Delivery Boy Work Area");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 34, 581, -1));

        lblDriverSex.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lblDriverSex.setForeground(new java.awt.Color(25, 56, 82));
        lblDriverSex.setText("Organization Type ");
        add(lblDriverSex, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 200, -1, -1));

        lblDriverAge.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lblDriverAge.setForeground(new java.awt.Color(25, 56, 82));
        lblDriverAge.setText("Organization Type ");
        add(lblDriverAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 170, -1, -1));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(25, 56, 82));
        jLabel3.setText("Gender");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, -1, -1));

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(25, 56, 82));
        jLabel7.setText("Driver Name");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, -1, 20));

        lblDriverName.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lblDriverName.setForeground(new java.awt.Color(25, 56, 82));
        lblDriverName.setText("Organization Type ");
        add(lblDriverName, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 140, -1, -1));

        jLabel10.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(25, 56, 82));
        jLabel10.setText("Age");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, -1, -1));

        btnDeleteItem2.setBackground(new java.awt.Color(255, 255, 255));
        btnDeleteItem2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnDeleteItem2.setForeground(new java.awt.Color(25, 56, 82));
        btnDeleteItem2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnDeleteItem2.setText("Delievered");
        btnDeleteItem2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnDeleteItem2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnDelieverMousePressed(evt);
            }
        });
        add(btnDeleteItem2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 450, 138, 35));

        btnDeleteItem3.setBackground(new java.awt.Color(255, 255, 255));
        btnDeleteItem3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnDeleteItem3.setForeground(new java.awt.Color(25, 56, 82));
        btnDeleteItem3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnDeleteItem3.setText("Pick Up");
        btnDeleteItem3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnDeleteItem3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnPickupMousePressed(evt);
            }
        });
        add(btnDeleteItem3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 138, 35));
    }// </editor-fold>//GEN-END:initComponents

    private void btnDelieverMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDelieverMousePressed
        // TODO add your handling code here:
        
        int selectedAdminRequestTableRow = driverJTable.getSelectedRow();            //bottom table
        
        
        if (selectedAdminRequestTableRow < 0){
            
            JOptionPane.showMessageDialog(null, "Please Select a request row from  table!");
            return;
        }
        
        FoodWorkRequest requestReq = (FoodWorkRequest)driverJTable.getValueAt(selectedAdminRequestTableRow, 0);
        if(requestReq.getStatus().equals("Delivered")){
            JOptionPane.showMessageDialog(null, "You have already delivered the Food Order!");
            return;
        }
        requestReq.setStatus("Delivered");
        requestReq.setDeliveryTimestamp(new Date());
        
        populateTable();
        
    }//GEN-LAST:event_btnDelieverMousePressed

    private void btnPickupMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPickupMousePressed
        // TODO add your handling code here:
        int selectedAdminRequestTableRow = driverJTable.getSelectedRow();            //bottom table
        
        
        if (selectedAdminRequestTableRow < 0){
            
            JOptionPane.showMessageDialog(null, "Please Select a request row from  table!");
            return;
        }
        
        
        FoodWorkRequest requestReq = (FoodWorkRequest)driverJTable.getValueAt(selectedAdminRequestTableRow, 0);
        if(requestReq.getStatus().equals("Picked Up")){
            JOptionPane.showMessageDialog(null, "You have already Picked Up the Order!");
            return;
        }
        requestReq.setStatus("Picked Up");
        requestReq.setDeliveryTimestamp(new Date());
        JOptionPane.showMessageDialog(null, "PickUp Task Completed Succefully");
        populateTable();
        
    }//GEN-LAST:event_btnPickupMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnDeleteItem2;
    private javax.swing.JLabel btnDeleteItem3;
    private javax.swing.JTable driverJTable;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDriverAge;
    private javax.swing.JLabel lblDriverName;
    private javax.swing.JLabel lblDriverSex;
    // End of variables declaration//GEN-END:variables
}
