/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.RestaurantAdminRole;

import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

/**
 *
 * @author Jayesh Nagarkar
 */
public class RestaurantProcessOrderJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RestaurantOrderDetailsJPanel
     */
    public RestaurantProcessOrderJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        txtFoodDishName = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblImage = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        restaurantAdminMenuJTable = new javax.swing.JTable();
        btnUploadImage = new javax.swing.JLabel();
        txtNoOfServing = new javax.swing.JTextField();
        txtImagePath = new javax.swing.JTextField();
        lblQuantity1 = new javax.swing.JLabel();
        btnDeleteItem2 = new javax.swing.JLabel();
        comboDeliveryManList = new javax.swing.JComboBox<>();
        lblQuantity = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/emergency512icon.png"))); // NOI18N
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 22, -1, -1));

        txtFoodDishName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/emergencyEmployee512xxx.png"))); // NOI18N
        add(txtFoodDishName, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 200, -1, -1));

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(25, 56, 82));
        jLabel8.setText("Build Order");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 190, -1));
        add(lblImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 460, 330, 180));

        restaurantAdminMenuJTable.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        restaurantAdminMenuJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Food Description", "No Of Serves"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(restaurantAdminMenuJTable);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, -1, 180));

        btnUploadImage.setBackground(new java.awt.Color(255, 255, 255));
        btnUploadImage.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnUploadImage.setForeground(new java.awt.Color(25, 56, 82));
        btnUploadImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnUploadImage.setText("View Food Image");
        btnUploadImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnUploadImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnUploadImagePressed(evt);
            }
        });
        add(btnUploadImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 420, 138, 20));

        txtNoOfServing.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        txtNoOfServing.setForeground(new java.awt.Color(25, 56, 82));
        txtNoOfServing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNoOfServingActionPerformed(evt);
            }
        });
        add(txtNoOfServing, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 370, 240, 30));
        add(txtImagePath, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 230, 220, -1));

        lblQuantity1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lblQuantity1.setForeground(new java.awt.Color(25, 56, 82));
        lblQuantity1.setText("No Of Servings");
        lblQuantity1.setToolTipText("");
        add(lblQuantity1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, 110, -1));

        btnDeleteItem2.setBackground(new java.awt.Color(255, 255, 255));
        btnDeleteItem2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnDeleteItem2.setForeground(new java.awt.Color(25, 56, 82));
        btnDeleteItem2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnDeleteItem2.setText("Send Order");
        btnDeleteItem2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnDeleteItem2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnDeleteItem2btnSendMousePressed(evt);
            }
        });
        add(btnDeleteItem2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 650, 138, 35));

        comboDeliveryManList.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        comboDeliveryManList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(comboDeliveryManList, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 660, 134, -1));

        lblQuantity.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lblQuantity.setForeground(new java.awt.Color(25, 56, 82));
        lblQuantity.setText("Delivery Man:");
        lblQuantity.setToolTipText("");
        add(lblQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 660, 90, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtNoOfServingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNoOfServingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNoOfServingActionPerformed

    private void btnDeleteItem2btnSendMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteItem2btnSendMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteItem2btnSendMousePressed

    private void btnUploadImagePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUploadImagePressed
        // TODO add your handling code here:
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        String filename = f.getAbsolutePath();
        txtImagePath.setText(filename);
        //Image getAbsolutePath = null;
        ImageIcon icon = new ImageIcon(filename);
        Image image = icon.getImage().getScaledInstance(lblImage.getWidth(), lblImage.getHeight(), java.awt.Image.SCALE_SMOOTH );  //Image.SCALE_SMOOTH
        icon = new ImageIcon( image );
        lblImage.setIcon(icon);
    }//GEN-LAST:event_btnUploadImagePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnDeleteItem2;
    private javax.swing.JLabel btnUploadImage;
    private javax.swing.JComboBox<String> comboDeliveryManList;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblQuantity;
    private javax.swing.JLabel lblQuantity1;
    private javax.swing.JTable restaurantAdminMenuJTable;
    private javax.swing.JLabel txtFoodDishName;
    private javax.swing.JTextField txtImagePath;
    private javax.swing.JTextField txtNoOfServing;
    // End of variables declaration//GEN-END:variables
}
