/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.IndividualReceiverOrganizationAdminRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Menu.Item;
import Business.Network.Network;
import Business.Organization.IndividualFoodDonorOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.Utils.TableColors;
import Business.WorkQueue.FoodWorkRequest;
import Business.WorkQueue.IndividualWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jayesh Nagarkar
 */
public class IndividualReceiverWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form IndividualReceiverWorkAreaJPanel
     */
    JPanel userProcessContainer;
    UserAccount account;
    Organization organization;
    Enterprise enterprise;
    Network network;
    EcoSystem business;
    
    public IndividualReceiverWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise,Network network, EcoSystem business) {
        initComponents();
        individualReceiverOrganizationJTable.getTableHeader().setDefaultRenderer(new TableColors());
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.organization = organization;
        this.enterprise = enterprise;
        this.network = network;
        this.business = business;
        populateTable();
                
                
    }
    
    public void populateTable(){
        DefaultTableModel model = (DefaultTableModel)individualReceiverOrganizationJTable.getModel();
        model.setRowCount(0);
        System.out.println("-------------lin number 54 small ");
        for(Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()){
            for(Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
                if(organization instanceof IndividualFoodDonorOrganization){
                    IndividualFoodDonorOrganization org = (IndividualFoodDonorOrganization)organization;
                    Object[] row = new Object[5];
                    for(Item item : org.getMenu().getItemList()){
                        System.out.println("----linenumber 61" + item);
                        row[0] = item;
                        row[1] = item.getDescription();
                        //row[2] = item.getNumberOfServings();
                        row[2] = item.getPostdate();
                        row[3] = item.getLocationOfIndividual();
                        row[4] = item.getItemStatus();
                        model.addRow(row);
                                 
                    }
                }
            }
        }
    }
    public void resetFields(){
        ImageIcon icon = new ImageIcon("");
        Image image = icon.getImage().getScaledInstance(lblImage.getWidth(), lblImage.getHeight(), java.awt.Image.SCALE_SMOOTH );  //Image.SCALE_SMOOTH
        icon = new ImageIcon( image );
        lblImage.setIcon(icon);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        individualReceiverOrganizationJTable = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnSubmit3 = new javax.swing.JLabel();
        lblImage = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        individualReceiverOrganizationJTable.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        individualReceiverOrganizationJTable.setForeground(new java.awt.Color(25, 56, 82));
        individualReceiverOrganizationJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Item Id", "Name", "Date Of posting", "Location", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        individualReceiverOrganizationJTable.setSelectionBackground(new java.awt.Color(56, 90, 174));
        individualReceiverOrganizationJTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                individualReceiverOrganizationJTableMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(individualReceiverOrganizationJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 111, 670, 157));

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(25, 56, 82));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Individual Receiver");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 34, 581, -1));

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(25, 56, 82));
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, -1, -1));

        btnSubmit3.setBackground(new java.awt.Color(255, 255, 255));
        btnSubmit3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnSubmit3.setForeground(new java.awt.Color(25, 56, 82));
        btnSubmit3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSubmit3.setText("Claim");
        btnSubmit3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnSubmit3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnClaimMousePressed(evt);
            }
        });
        add(btnSubmit3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 510, 138, 35));

        lblImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(lblImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 270, 180));
    }// </editor-fold>//GEN-END:initComponents

    private void btnClaimMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClaimMousePressed
       int selectedRow = individualReceiverOrganizationJTable.getSelectedRow();
       if(selectedRow < 0){
           JOptionPane.showMessageDialog(null, "Please select any item inorder to claim!");
       }
       Item item = (Item)individualReceiverOrganizationJTable.getValueAt(selectedRow, 0);
       item.setItemStatus("Claimed");
       FoodWorkRequest request = new FoodWorkRequest();
       request.setRequestingOrganizationType(organization.getType());
       request.setRequestingOrganizationUser(account);
       request.setRequestingOrganiztionName(organization);
       request.setDonorOrganizationType(Organization.Type.IndividualDonator);
       organization.getWorkQueue().addRequest(request);
       
       JOptionPane.showMessageDialog(null, "You claimed Food Item successfully!");
       populateTable();
       resetFields();
       
    }//GEN-LAST:event_btnClaimMousePressed

    private void individualReceiverOrganizationJTableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_individualReceiverOrganizationJTableMousePressed
        // TODO add your handling code here:
       int selectedRow = individualReceiverOrganizationJTable.getSelectedRow();
       
        Item item = (Item)individualReceiverOrganizationJTable.getValueAt(selectedRow, 0);
        //Image getAbsolutePath = null;
        ImageIcon icon = new ImageIcon(item.getImagePath());
        Image image = icon.getImage().getScaledInstance(lblImage.getWidth(), lblImage.getHeight(), java.awt.Image.SCALE_SMOOTH );  //Image.SCALE_SMOOTH
        icon = new ImageIcon( image );
        lblImage.setIcon(icon);
    }//GEN-LAST:event_individualReceiverOrganizationJTableMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnSubmit3;
    private javax.swing.JTable individualReceiverOrganizationJTable;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblImage;
    // End of variables declaration//GEN-END:variables
}
